version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  verbosity: minimal
before_package:
- ps: Copy-Item C:\projects\Project-Atlas\$env:CONFIGURATION\Project-Atlas.exe C:\projects\Project-Atlas\Game\.
artifacts:
- path: Game
  name: Project Atlas
deploy:
- provider: GitHub
  description: Project Atlas Engine
  auth_token:
    secure: QtTBORPKFi7Nuf+725DnjsiqZiiBFjfxM/MV9TcByhwXe16rz3f/F+iWSCQyJUjY
  draft: true
