version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  verbosity: minimal
before_package:
- ps: Copy-Item C:\projects\Project-Alpha\Project-Alpha\$env:CONFIGURATION\Project-Alpha.exe C:\projects\Project-Alpha\Game\.
artifacts:
- path: Project-Alpha\Game
  name: Project Alpha
deploy:
- provider: GitHub
  description: Project Atlas Engine
  auth_token:
    secure: piE1WY+KQYZkBVZ0eaCkCJJru7Wzo0OObLas5xrwYWRROcQivrqnrCrK++IW59H9
  draft: true
